### ISSUE TITLE
install.bat Typed Error: set "python_exec=..\..\..\python_embedded\python.exe" should be "python_embeded"

### ISSUE THREAD

**Issue by Erwin11** [ManglerFTW/ComfyI2I#12]
install.bat 
Typed Error:
line 4 :  set "python_exec=..\..\..\python_embedded\python.exe" 
should be "python_embeded", all code below:

set "python_exec=..\..\..\python_embeded\python.exe"

**Comment by ManglerFTW** [comment]
Thank you for catching that. I've updated the repo with the new change.
