### ISSUE TITLE
Problem with the installation of the node set

### ISSUE THREAD

**Issue by sborys-ai** [ManglerFTW/ComfyI2I#4]
When trying to install this package through ComfyUI Manager, I receive the following errors:

ComfyUI-Manager: EXECUTE => ['/home/sborys/miniconda3/envs/old_python/bin/python3', '-m', 'pip', 'install', 'subprocess']
[!] ERROR: Could not find a version that satisfies the requirement subprocess (from versions: none)
[!] ERROR: No matching distribution found for subprocess
install script failed: https://github.com/ManglerFTW/ComfyI2I

ComfyUI-Manager: EXECUTE => ['/home/sborys/miniconda3/envs/old_python/bin/python3', '-m', 'pip', 'install', 'math']
[!] ERROR: Could not find a version that satisfies the requirement math (from versions: none)
[!] ERROR: No matching distribution found for math
install script failed: https://github.com/ManglerFTW/ComfyI2I

ComfyUI-Manager: EXECUTE => ['/home/sborys/miniconda3/envs/old_python/bin/python3', '-m', 'pip', 'install', 'skimage']
 Collecting skimage
   Using cached skimage-0.0.tar.gz (757 bytes)
   Preparing metadata (setup.py): started
   Preparing metadata (setup.py): finished with status 'error'
[!]   error: subprocess-exited-with-error
[!]   
[!]   × python setup.py egg_info did not run successfully.
[!]   │ exit code: 1
[!]   ╰─> [3 lines of output]
[!]       
[!]       *** Please install the `scikit-image` package (instead of `skimage`) ***
[!]       
[!]       [end of output]
[!]   
[!]   note: This error originates from a subprocess, and is likely not a problem with pip.
[!] error: metadata-generation-failed
[!] 
[!] × Encountered error while generating package metadata.
[!] ╰─> See above for output.
[!] 
[!] note: This is an issue with the package mentioned above, not pip.
[!] hint: See above for details.
install script failed: https://github.com/ManglerFTW/ComfyI2I

ComfyUI-Manager: EXECUTE => ['/home/sborys/miniconda3/envs/old_python/bin/python3', '-m', 'pip', 'install', 'scipy']
 Requirement already satisfied: scipy in /home/sborys/miniconda3/envs/old_python/lib/python3.10/site-packages (1.9.1)
 Requirement already satisfied: numpy<1.25.0,>=1.18.5 in /home/sborys/miniconda3/envs/old_python/lib/python3.10/site-packages (from scipy) (1.23.5)

ComfyUI-Manager: EXECUTE => ['/home/sborys/miniconda3/envs/old_python/bin/python3', '-m', 'pip', 'install', 'cv2']
[!] ERROR: Could not find a version that satisfies the requirement cv2 (from versions: none)
[!] ERROR: No matching distribution found for cv2
install script failed: https://github.com/ManglerFTW/ComfyI2I

When attempting to install this package manually, I encounter the following errors:

ComfyUI/custom_nodes/ComfyI2I$ pip3 install -r requirements.txt

ERROR: Could not find a version that satisfies the requirement subprocess (from versions: none)
ERROR: No matching distribution found for subprocess

after which the process is terminated.

I've tried running it on two different computers, in different environments, with the latest version of Python and with an older one. 
The result is the same everywhere. What can be done about this?

**Comment by Kinglord** [comment]
I was able to get this working by editing the requirements.txt file as mentioned in my issue that I opened. Hopefully it will help you as well.

**Comment by ManglerFTW** [comment]
Thank you for your reply. I will be addressing issues with the next update coming sometime within the week.

**Comment by ManglerFTW** [comment]
This issue should be fixed now. Please check on your end.

**Comment by sborys-ai** [comment]
Thanks! It's all good now.
