### ISSUE TITLE
Tried workflow.js example, but I get issues in the maskopsnode and inpaint segments

### ISSUE THREAD

**Issue by freke70** [ManglerFTW/ComfyI2I#5]
got prompt
3
3
3
Traceback (most recent call last):
  File "/root/ComfyUI/execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/root/ComfyUI/execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/root/ComfyUI/execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/root/ComfyUI/custom_nodes/ComfyI2I/ComfyI2I.py", line 1429, in get_region
    Cut_Image = CutByMask(image, region, force_resize_width, force_resize_height, mask_mapping_optional)
  File "/root/ComfyUI/custom_nodes/ComfyI2I/ComfyI2I.py", line 622, in CutByMask
    image = image[mask_mapping_optional]
IndexError: tensors used as indices must be long, int, byte or bool tensors

To be honest, I have no idea what to fill in there.
I figured the workflow.js would have something workeable filled in already, but it gave errors from the start.
![2023-09-14_17h59_43](https://github.com/ManglerFTW/ComfyI2I/assets/21170212/55b68991-e2f8-4b5e-b0d4-e82d13f9ce6b)

If you happen to have a working workflow.js  example that might set me on the right path.

Thanks!

**Comment by ManglerFTW** [comment]
I will take a look at this soon. I'm wondering since the issue is with the separate_mask option, if you change it to 0 it might work. If so, I may have to add a check in the code to see how many segments are initially in the mask.

**Comment by Luzido** [comment]
Hi there, just wanted to report, that I have the same issue. And yes, if I remember correctly, with a single mask or a combined mask, the error doesn't appear.
I'd really appreciate a fix. Great work btw!
