### ISSUE TITLE
Bad Requirements.txt for Windows ComfyUI Standalone?

### ISSUE THREAD

**Issue by Kinglord** [ManglerFTW/ComfyI2I#7]
Hey there, I'm not sure if this is just me or if this will help others, but I'm running the latest version of ComfyUI Standalone on windows on python 3.10.9 and the requirements file would not work for me at all. I was able to work through it and make some edits and get everything working. If anyone else is having this problem just edit the requirements.txt file to the following and it should work.

```
numpy
torch
torchvision
tensorflow
scikit-image
scipy
opencv-python
```

**Comment by ManglerFTW** [comment]
I will admit, there are some apps on the requirements that are automatically installed with python that I didn't realize. I will be addressing this issue in the next update later this week.

**Comment by Kinglord** [comment]
No worries! Appreciate all the work you've done and this is fairly minor as long as you know you way around python. For those less inclined, it just means the install bat won't complete properly which is what makes the node not show up even though it doesn't throw a server error (at least it didn't for me).

**Comment by ManglerFTW** [comment]
I've pushed the suggested requirements fixed to the repo. It should be fixed now. Thanks again for the heads up!
